name: Deploy to OCI
on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt install -y openssh-client

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with: 
          ssh-private-key: ${{ secrets.OCI_SSH_KEY }}
      - name: Deploy to OCI
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.OCI_USER }}@${{ secrets.OCI_PUBLIC_IP }}
          cd /home/ubuntu/oci-cici
          git pull origin master
          # 파이썬 스크립트 실행
          python3 hello.py
          
            
